[workspace]
authors = ["elaprelleboucher"]
channels = ["conda-forge"]
name = "cue_simulation"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]

# Python
python = "*"
numpy = "*"

# DÃ©veloppement
autopep8 = "*"
coverage = "*"
pytest = "*"

[tasks]

# Mono
main = "python main.py"
config = "python config.py"
cover_get = "coverage run -m pytest engine"
cover_show = "coverage html"
format = "autopep8 --in-place --recursive ./"
go = "python main_dev.py"
test = "pytest engine"
testx = "pytest -s -x engine"
print_test = "pytest -s engine"

# Multi
coverage = {depends-on = ["cover_get", "cover_show"]}
validate = {depends-on = ["format", "coverage", "main"]}
